### ISSUE TITLE
Debug gl_example.py

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/pyopenxr#41]
It's not working, but it's getting close.

**Comment by cmbruns** [comment]
Plus it's Windows specific. It should be generalized for linux.

https://github.com/cmbruns/pyopenxr/blob/main/examples/gl_example.py
is based on
https://github.com/jherico/OpenXR-Samples/blob/master/src/examples/sdl2_gl_single_file_example_c.cpp

**Comment by jherico** [comment]
#42 fixes it and at least gets it rendering to a headset on my system.  The source example could use some work I think because I don't think it properly follows the expected flow of events based on session state.

**Comment by cmbruns** [comment]
Fixed by #42
