### ISSUE TITLE
how to use this framework as a silent background process ?

### ISSUE THREAD

**Issue by nukadelic** [cmbruns/pyopenxr#46]
I want to record the hmd and the controllers positions and rotations into a csv file while playing a steam-vr game , would it be possible at the current state of the library ? where should i start looking how to do that ?

**Comment by cmbruns** [comment]
If you can figure out how to do that using the OpenXR SDK in C, we can probably figure out how to make it work in pyopenxr. Otherwise you might need to wait a long time.
