### ISSUE TITLE
Not working with HTC Vive

### ISSUE THREAD

**Issue by drakeerv** [cmbruns/pyopenxr#58]
Currently I have a HTC Vive but it wont work. I try the HMD Track example and it says, "Exception has occurred: FormFactorUnavailableError". The other two examples give assertion errors. Also, when will pyglet be supported and do you have a discord server for this project?

**Comment by drakeerv** [comment]
Did a little more digging and as it turns out its trying to use my disconnected HP headset and not my stream vr one. Is there a way to get different headsets?

**Comment by cmbruns** [comment]
I don't know how to change the active openxr runtime when you have more than one. If you figure it out please let us know.

**Comment by drakeerv** [comment]
Fixed it! I was just playing an openxr game and it had the same issue. I looked it up and apparently I never changed the openxr environment back to steamvr in the steamvr dev settings.
