### ISSUE TITLE
Please update for OpenXR 1.0.23

### ISSUE THREAD

**Issue by paulmelis** [cmbruns/pyopenxr#67]
Hi, great package, thanks for making this available! Could you make a new build for the just released https://github.com/KhronosGroup/OpenXR-SDK/releases/tag/release-1.0.23 ?

**Comment by cmbruns** [comment]
@paulmelis Thank you for the heads up. I knew there was a new release; but I was trying to complete a working hello_xr example before releasing. That's taking longer than I had hoped, so I will shift gears and problably update the bindings in the next day or so.

Out of curiosity, is there a specific reason you are eager for the latest release?

**Comment by cmbruns** [comment]
New release is now live at https://github.com/cmbruns/pyopenxr/releases/tag/1.0.2301
